{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'c:\\\\Users\\\\HP\\\\OneDrive\\\\Desktop\\\\resume_ready_projects\\\\text_summarizer_project\\\\research'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.chdir('../')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'c:\\\\Users\\\\HP\\\\OneDrive\\\\Desktop\\\\resume_ready_projects\\\\text_summarizer_project'"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dataclasses import dataclass\n",
    "from pathlib import Path\n",
    "\n",
    "@dataclass(frozen=True)\n",
    "class DataIngestionConfig:\n",
    "    root_dir: Path\n",
    "    source_URL: str\n",
    "    local_data_file: Path\n",
    "    unzip_dir: Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "from textSummarizer.constants import *\n",
    "from textSummarizer.utils.common import read_yaml, create_directories"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "class ConfigurationManager:\n",
    "    def __init__(\n",
    "            self,config_filepath = CONFIG_FILE_PATH,\n",
    "            params_filepath = PARAMS_FILE_PATH):\n",
    "        \n",
    "        self.config = read_yaml(config_filepath)\n",
    "        self.params = read_yaml(params_filepath)\n",
    "\n",
    "        create_directories([self.config.artifacts_roots])\n",
    "\n",
    "    def get_data_ingestion_config(self) -> DataIngestionConfig:\n",
    "        config = self.config.data_ingestion\n",
    "\n",
    "        create_directories([config.root_dir])\n",
    "        \n",
    "        data_ingestion_config = DataIngestionConfig(\n",
    "            root_dir = config.root_dir,\n",
    "            source_URL = config.source_URL,\n",
    "            local_data_file= config.local_data_file,\n",
    "            unzip_dir=config.unzip_dir\n",
    "        )\n",
    "\n",
    "        return data_ingestion_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import urllib.request as request\n",
    "import zipfile\n",
    "from textSummarizer.logging import logger\n",
    "from textSummarizer.utils.common import get_size"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "class DataIngestion:\n",
    "    def __init__(self,config:DataIngestionConfig):\n",
    "        self.config = config\n",
    "\n",
    "    def download_file(self):\n",
    "        if not os.path.exists(self.config.local_data_file):\n",
    "            filename,headers = request.urlretrieve(\n",
    "                url=self.config.source_URL,\n",
    "                filename=self.config.local_data_file\n",
    "            )\n",
    "            logger.info(f\"{filename} downloaded! with following info :\\n{headers}\")\n",
    "\n",
    "        else:\n",
    "            logger.info(f\"File already exist of size: {get_size(Path(self.config.local_data_file))}\")\n",
    "\n",
    "\n",
    "    def extract_zip_file(self):\n",
    "        unzip_path = self.config.unzip_dir\n",
    "        os.makedirs(unzip_path,exist_ok=True)\n",
    "        with zipfile.ZipFile(self.config.local_data_file,'r') as zip_ref:\n",
    "            zip_ref.extractall(unzip_path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 2, in <module>\n",
      "    config = ConfigurationManager()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 6, in __init__\n",
      "    self.config = read_yaml(config_filepath)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 15, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: config\\\\config.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 2, in <module>\n",
      "    config = ConfigurationManager()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 6, in __init__\n",
      "    self.config = read_yaml(config_filepath)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 15, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: config\\\\config.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 2, in <module>\n",
      "    config = ConfigurationManager()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 7, in __init__\n",
      "    self.params = read_yaml(params_filepath)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 15, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: params.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 2, in <module>\n",
      "    config = ConfigurationManager()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 7, in __init__\n",
      "    self.params = read_yaml(params_filepath)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 15, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: params.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 2, in <module>\n",
      "    config = ConfigurationManager()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 9, in __init__\n",
      "    create_directories([self.config.artifacts_roots])\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 27, in create_directories\n",
      "    logger.info(f\"directory created: {path}\")\n",
      "Message: 'directory created: artifacts'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 2, in <module>\n",
      "    config = ConfigurationManager()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 9, in __init__\n",
      "    create_directories([self.config.artifacts_roots])\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 27, in create_directories\n",
      "    logger.info(f\"directory created: {path}\")\n",
      "Message: 'directory created: artifacts'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 3, in <module>\n",
      "    data_ingestion_config = config.get_data_ingestion_config()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 14, in get_data_ingestion_config\n",
      "    create_directories([config.root_dir])\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 27, in create_directories\n",
      "    logger.info(f\"directory created: {path}\")\n",
      "Message: 'directory created: artifacts/data_ingestion'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 3, in <module>\n",
      "    data_ingestion_config = config.get_data_ingestion_config()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\2068471623.py\", line 14, in get_data_ingestion_config\n",
      "    create_directories([config.root_dir])\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"c:\\users\\hp\\onedrive\\desktop\\resume_ready_projects\\text_summarizer_project\\src\\textSummarizer\\utils\\common.py\", line 27, in create_directories\n",
      "    logger.info(f\"directory created: {path}\")\n",
      "Message: 'directory created: artifacts/data_ingestion'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 5, in <module>\n",
      "    data_ingestion.download_file()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\951840575.py\", line 11, in download_file\n",
      "    logger.info(f\"{filename} downloaded! with following info :\\n{headers}\")\n",
      "Message: 'artifacts/data_ingestion/data.zip downloaded! with following info :\\nConnection: close\\nContent-Length: 7903594\\nCache-Control: max-age=300\\nContent-Security-Policy: default-src \\'none\\'; style-src \\'unsafe-inline\\'; sandbox\\nContent-Type: application/zip\\nETag: \"dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca\"\\nStrict-Transport-Security: max-age=31536000\\nX-Content-Type-Options: nosniff\\nX-Frame-Options: deny\\nX-XSS-Protection: 1; mode=block\\nX-GitHub-Request-Id: E791:2B9E23:21F331:2B6F30:66F8D5A1\\nAccept-Ranges: bytes\\nDate: Sun, 29 Sep 2024 04:20:50 GMT\\nVia: 1.1 varnish\\nX-Served-By: cache-del21742-DEL\\nX-Cache: MISS\\nX-Cache-Hits: 0\\nX-Timer: S1727583649.443042,VS0,VE709\\nVary: Authorization,Accept-Encoding,Origin\\nAccess-Control-Allow-Origin: *\\nCross-Origin-Resource-Policy: cross-origin\\nX-Fastly-Request-ID: 398306bc74431c98f21950a30da516ed360b5330\\nExpires: Sun, 29 Sep 2024 04:25:50 GMT\\nSource-Age: 0\\n\\n'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 666, in format\n",
      "    s = self.formatMessage(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
      "    return self._style.format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 434, in format\n",
      "    return self._format(record)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\logging\\__init__.py\", line 430, in _format\n",
      "    return self._fmt % record.__dict__\n",
      "ValueError: unsupported format character ']' (0x5d) at index 51\n",
      "Call stack:\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3048, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3103, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3308, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\HP\\anaconda3\\envs\\textsu_3.9\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3550, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\1803582706.py\", line 5, in <module>\n",
      "    data_ingestion.download_file()\n",
      "  File \"C:\\Users\\HP\\AppData\\Local\\Temp\\ipykernel_14060\\951840575.py\", line 11, in download_file\n",
      "    logger.info(f\"{filename} downloaded! with following info :\\n{headers}\")\n",
      "Message: 'artifacts/data_ingestion/data.zip downloaded! with following info :\\nConnection: close\\nContent-Length: 7903594\\nCache-Control: max-age=300\\nContent-Security-Policy: default-src \\'none\\'; style-src \\'unsafe-inline\\'; sandbox\\nContent-Type: application/zip\\nETag: \"dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca\"\\nStrict-Transport-Security: max-age=31536000\\nX-Content-Type-Options: nosniff\\nX-Frame-Options: deny\\nX-XSS-Protection: 1; mode=block\\nX-GitHub-Request-Id: E791:2B9E23:21F331:2B6F30:66F8D5A1\\nAccept-Ranges: bytes\\nDate: Sun, 29 Sep 2024 04:20:50 GMT\\nVia: 1.1 varnish\\nX-Served-By: cache-del21742-DEL\\nX-Cache: MISS\\nX-Cache-Hits: 0\\nX-Timer: S1727583649.443042,VS0,VE709\\nVary: Authorization,Accept-Encoding,Origin\\nAccess-Control-Allow-Origin: *\\nCross-Origin-Resource-Policy: cross-origin\\nX-Fastly-Request-ID: 398306bc74431c98f21950a30da516ed360b5330\\nExpires: Sun, 29 Sep 2024 04:25:50 GMT\\nSource-Age: 0\\n\\n'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    config = ConfigurationManager()\n",
    "    data_ingestion_config = config.get_data_ingestion_config()\n",
    "    data_ingestion = DataIngestion(config=data_ingestion_config)\n",
    "    data_ingestion.download_file()\n",
    "    data_ingestion.extract_zip_file()\n",
    "except Exception as e:\n",
    "    raise e"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "textsu_3.9",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
